# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = ".dist"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[[headers]]
  for = "/*"
  [headers.values]
    referrer-policy = "same-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
